### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Jucyfer** [McJtyMods/RFToolsBase#37]
forge-31.2.0
mcjtylib-1.15-4.1.13
rftoolsbase-1.15-1.1.10
rftoolsbuilder-1.15-2.1.16
rftoolsutility-1.15-2.1.20

There comes three error. Then the client sudden crashed and disappeared, with no report window.
stacktraces in logs below:

 [modloading-worker-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: rftoolsbase, class mcjty.rftoolsbase.RFToolsBase
java.lang.NoSuchMethodError: net.minecraftforge.registries.DeferredRegister.create(Lnet/minecraftforge/registries/IForgeRegistry;Ljava/lang/String;)Lnet/minecraftforge/registries/DeferredRegister;
	at mcjty.rftoolsbase.setup.Registration.<clinit>(Registration.java:19) ~[?:1.15-1.1.10]
	at mcjty.rftoolsbase.modules.crafting.CraftingModule.<clinit>(CraftingModule.java:22) ~[?:1.15-1.1.10]
	at mcjty.rftoolsbase.RFToolsBase.setupModules(RFToolsBase.java:57) ~[?:1.15-1.1.10]
	at mcjty.rftoolsbase.RFToolsBase.<init>(RFToolsBase.java:41) ~[?:1.15-1.1.10]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) ~[?:31.2]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_261]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]
-------------------------------------------------------------------------------------------------------------------
 [modloading-worker-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: rftoolsutility, class mcjty.rftoolsutility.RFToolsUtility
java.lang.NoSuchMethodError: net.minecraftforge.registries.DeferredRegister.create(Lnet/minecraftforge/registries/IForgeRegistry;Ljava/lang/String;)Lnet/minecraftforge/registries/DeferredRegister;
	at mcjty.rftoolsutility.setup.Registration.<clinit>(Registration.java:25) ~[?:1.15-2.1.20]
	at mcjty.rftoolsutility.modules.crafter.CrafterModule.<clinit>(CrafterModule.java:23) ~[?:1.15-2.1.20]
	at mcjty.rftoolsutility.RFToolsUtility.setupModules(RFToolsUtility.java:49) ~[?:1.15-2.1.20]
	at mcjty.rftoolsutility.RFToolsUtility.<init>(RFToolsUtility.java:34) ~[?:1.15-2.1.20]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) ~[?:31.2]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_261]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]
-------------------------------------------------------------------------------------------------------------------
 [modloading-worker-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: mcjtylib, class mcjty.lib.McJtyLib
java.lang.NoSuchMethodError: net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(Lnet/minecraftforge/api/distmarker/Dist;Ljava/util/function/Supplier;)V
	at mcjty.lib.McJtyLib.<init>(McJtyLib.java:44) ~[?:1.15-4.1.13]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) ~[?:31.2]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_261]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]

**Comment by McJty** [comment]
Is that forge recent enough? Did you try updating?

**Comment by Jucyfer** [comment]
uhh,my forge version is forge-31.2.0, which is the stable version based on mc-1.15.2.. I've tried this method in my own mod, and that works. but the same method failed in RFTools.
thats so weird.
