### ISSUE TITLE
java.lang.NoSuchMethodError on launch (1.19.2)

### ISSUE THREAD

**Issue by rossjspencer** [McJtyMods/RFToolsBase#96]
**rftoolsbase and builder "fail to load correctly", rfdimensions doesn't have this issue

Likely a me problem, but mod/forge versions seem to line up and I can't identify any other obvious issues.**

Crash report below:
[modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: rftoolsbase, class mcjty.rftoolsbase.RFToolsBase
java.lang.NoSuchMethodError: 'void mcjty.rftoolsbase.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
	at mcjty.rftoolsbase.setup.ModSetup.<init>(ModSetup.java:22) ~[rftoolsbase-1.19.1-4.0.2.jar%23182!/:1.19.1-4.0.2]
	at mcjty.rftoolsbase.RFToolsBase.<clinit>(RFToolsBase.java:34) ~[rftoolsbase-1.19.1-4.0.2.jar%23182!/:1.19.1-4.0.2]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.8.jar%23193!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.8.jar%23192!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by McJty** [comment]
Update RFToolsBase (and probably your other rftools/mcjtylib mods too). It's outdated
